spring.application.name=PaymentService
spring.datasource.url=jdbc:postgresql://ep-damp-water-aowejbva-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_xMKLT3SOcan4&sslmode=require&channelBinding=require

# Database Credentials
#spring.datasource.username=your_database_username
#spring.datasource.password=your_database_password

# Driver and Dialect Configurations
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Behavior (updates schemas automatically based on your Entity classes)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true