server:
  port: 8084

grpc:
  server:
    port: 9092

spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/inventory_db
    url: jdbc:postgresql://ep-square-leaf-aonacrdd-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nSxw26BHZNUe&sslmode=require&channelBinding=require
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update