server:
  port: 8084

grpc:
  server:
    port: 9093

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_service_db?TimeZone=UTC
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: payment-group

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "org.example.sharedevents"


    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      spring.json.type.mapping: "paymentFailed:org.example.sharedevents.PaymentFailedEvent,paymentCompleted:org.example.sharedevents.PaymentSuccessEvent"
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer