apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init-db.sql: |
    CREATE DATABASE auth_service_db;
    CREATE DATABASE booking_service_db;
    CREATE DATABASE inventory_service_db;
    CREATE DATABASE payment_service_db;