apiVersion: apps/v1
kind: Deployment

metadata:
  name: booking-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: booking-service

  template:
    metadata:
      labels:
        app: booking-service

    spec:
      containers:
        - name: booking-service

          image: booking-service:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/booking_service_db

            - name: SPRING_DATASOURCE_USERNAME
              value: admin

            - name: SPRING_DATASOURCE_PASSWORD
              value: password

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

            - name: GRPC_INVENTORY_HOST
              value: inventory-service

            - name: GRPC_INVENTORY_PORT
              value: "9091"