apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          imagePullPolicy: IfNotPresent
          image: inventory-service:latest
          ports:
            - containerPort: 8083
            - containerPort: 9091
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/inventory_service_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092